server:
 port: 8888
spring:
 application:
  name: config-server
 cloud:
  config:
   server:
    git:
     uri: https://github.com/vux0501/cloud-config-server
     default-label: master
    bootstrap: false