server:
 port: 9999
spring:
 config:
  import: "optional:configserver:"
 application:
  name: API_GATEWAY
 cloud:
  config:
   uri: http://localhost:8888
  gateway:
   routes:
   - id: productService
     uri: http://localhost:4000/
     predicates:
     - Path=/product/**
   - id: cartService
     uri: http://localhost:4001/
     predicates:
     - Path=/cart/**
   - id: authService
     uri: http://localhost:8080/
     predicates:
     - Path=/**






